version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_db
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  rag-app:
    build: .
    container_name: pharma_rag_ui
    ports:
      - "8501:8501"
    environment:
      # Указываем приложению искать Ollama внутри Docker сети
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./src:/app/src
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  hf_cache:
